version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      npm-packages:
        patterns: [ "*" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      github-action-workflows:
        patterns: [ "*" ]
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
