name: 'Lint PR title preview (current branch, ignoreLabels enabled)'
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

permissions:
  contents: read
  pull-requests: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          STEPSECURITY_API_KEY: ${{ secrets.STEPSECURITY_API_KEY }}
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
